version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=matching_development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
  matching:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/matching
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
